---
- name: Create encrypted drive mountpoint
  file:
    path: "{{cloud_nas_mountpoint}}"
    state: directory
    owner: root
    group: users
    mode: u=rwx,g=rx,o=rx  

- name: PLEASE LOG IN AND MOUNT ENCRYPTED VOLUME TO CONTINUE
  ansible.builtin.shell: "mountpoint -q {{cloud_nas_mountpoint}}"
  register: cloud_nas_encrypted_drive_mountpoint
  until: cloud_nas_encrypted_drive_mountpoint.rc == 0
  retries: 30
  delay: 10

- debug:
   msg: "Encrypted drive mounted!"
  when: cloud_nas_encrypted_drive_mountpoint.rc == 0

- name: Create private root folder
  file:
    path: "{{cloud_nas_private_folders_root}}"
    state: directory
    owner: root
    group: users
    mode: u=rwx,g=rx,o-rwx  

- name: Create private folders for users
  file:
    path: "{{cloud_nas_private_folders_root}}/{{item.name}}"
    state: directory
    owner: "{{item.name}}"
    group: root
    mode: u=rwx,g-rwx,o-rwx
    recurse: yes
  with_items:
    - "{{cloud_nas_samba_users}}"
  no_log: True

- name: Create shared folders
  file:
    path: "{{item.path}}"
    state: directory
    group: "{{item.group}}"
    mode: "{{item.mode}}"
  with_items:
    - "{{cloud_nas_shared_folders}}"

- name: Create sftp authorized keys directory
  file:
    path: /etc/proftpd/authorized_keys
    state: directory
    mode: u=rwx,g=rx,o=rx
