---
- name: Configure base settings
  hosts: blank
  tasks:

    - name: Include role general/utils/roles/update-os
      include_role:
        name: "{{ collections_path }}/general/utils/roles/update-os"

    - name: Include role general/utils/roles/install-utils
      include_role:
        name: "{{ collections_path }}/general/utils/roles/install-utils"

    - name: Include role general/utils/roles/install-webmin
      include_role:
        name: "{{ collections_path }}/general/utils/roles/install-webmin"
        
    - name: Include role general/system/roles/set-usersandgroups
      include_role:
        name: "{{ collections_path }}/general/system/roles/set-usersandgroups"
      vars:
        set_usersandgroups_json: "{{json_host_settings}}"
 
    - name: Include role general/system/roles/set-network
      include_role:
        name: "{{ collections_path }}/general/system/roles/set-network"
      vars:
        set_network_json: "{{json_host_settings}}"

    - name: Include role general/system/roles/set-hostkeys
      include_role:
        name: "{{ collections_path }}/general/system/roles/set-hostkeys"
      vars:
        set_hostkeys_restart_service: false
        set_hostkeys_json: "{{json_host_settings}}"
        
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers
        
    - name: Delayed reboot
      shell: /usr/bin/sleep 5 && /usr/sbin/reboot
      async: 1
      poll: 0
      args:
        executable: /bin/bash
        
- name: Configure Gaia
  hosts: gaia
  gather_facts: no # gather_facts turned off not to fail waiting for host to be up
  tasks:

    - name: Wait 300 seconds, PLEASE START HOST BEFORE TIME'S UP
      ansible.builtin.wait_for_connection:
        #delay: 30
        timeout: 300
        
    - name: gather facts manually since they were turned off first
      setup:

    - name: Include role general/utils/roles/upgrade-packages
      include_role:
        name: "{{ collections_path }}/general/utils/roles/upgrade-packages"

    - name: Include role wares/dmz/roles/nordvpn
      include_role:
        name: "{{ collections_path }}/wares/dmz/roles/nordvpn"
      vars:
        nordvpn_install_linux_client: false
        nordvpn_ovpn_conf_file: '/etc/openvpn/nordvpn/ovpn_udp/uk2222.nordvpn.com.udp.ovpn'
        nordvpn_ovpn_conf_name: 'uk2222'
        nordvpn_login: 'sam@domain.org'
        nordvpn_password: 'P@55w0rd1'

    - name: Include role general/network/roles/tinyproxy
      include_role:
        name: "{{ collections_path }}/general/network/roles/tinyproxy"
      vars:
        tinyproxy_port: 8888
        tinyproxy_allow_networks: 
          - '127.0.0.1'
          - '192.168.1.0/24'

    - name: Include role general/network/roles/ipmasq
      include_role:
        name: "{{ collections_path }}/general/network/roles/ipmasq"
      vars:
        ipmasq_source: '192.168.1.0/24'
        ipmasq_destination: '0.0.0.0/0'
